FROM node:16-alpine

WORKDIR /app

# 设置 npm 使用阿里云镜像源
RUN npm config set registry https://registry.npmmirror.com \
    && npm config set sass_binary_site https://npmmirror.com/mirrors/node-sass/

# 复制 package.json 和 package-lock.json
COPY package*.json ./

# 安装依赖
RUN npm install

# 暴露端口
EXPOSE 3000

# 启动开发服务器
CMD ["npm", "start"] 