services:
  backend:
    build: ./backend
    container_name: aiempowerment-backend
    volumes:
      - ./backend/app.db:/app/app.db
      - ./backend/config:/app/config
      - ./backend/uploads:/app/uploads
      - ./backend/static:/app/static
    environment:
      - CONFIG_FILE=/app/config/default.yaml
      - SECRET_KEY=your-secret-key-here
    ports:
      - "8000:8000"
    networks:
      - app-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_ENV=production
        - REACT_APP_API_URL=/api/v1
    container_name: aiempowerment-frontend
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    networks:
      - app-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge